### ISSUE TITLE
Error: unexpected end of JSON input

### ISSUE THREAD

**Issue by tangel0v** [vouch/vouch-proxy#257] opened 2020-04-29 07:40 UTC
Hi to all. We are not be able to extract the information of the token received from a ADFS 2019 platform. We are using _oidc_ as OAuth provider instead of adfs because it didn't work with our configuration. 

After receiving the token, the logs show the following information and we received an error in our browser with the phrase "unexpected end of JSON input":

{"level":"debug","ts":1588088738.494023,"msg":"ptokens: &{PAccessToken:FULLVALIDTOKEN}"}
{"level":"info","ts":1588088738.548036,"msg":"OpenID userinfo body: "}
{"level":"error","ts":1588088738.5480857,"msg":"Error unmarshaling claims"}
{"level":"error","ts":1588088738.5480921,"msg":"unexpected end of JSON input"}

The body seems to be empty but the token received is valid and if you decrypt it, you will see all the claims. Here is an example of the decrypted token received by Vouch from the ADFS server: https://hasteb.in/yorazule.json (the information is changed and it's not real).

We are using Firefox 75.0 and Chrome 81 in Windows and Linux. Vouch is installed in Kubernetes via Helm.

We also have reviewed this issue [first](https://github.com/vouch/vouch-proxy/issues/135) without success.

```yaml
oauth:
  provider: oidc
  client_id: 438333b9-267b-435e-bf18-7b366421bb7h
  client_secret: CENSORED
  auth_url: https://fed.miserere.com/adfs/oauth2/authorize
  token_url: https://fed.miserere.com/adfs/oauth2/token
  user_info_url: https://fed.miserere.com/adfs/userinfo
  scopes:
    - http://vouch.miserere.com/openid
    - email
    - profile
  callback_url: https://vouch.gcp.miserere.com/auth
```

This is our full configuration: https://hasteb.in/eyonigab.yaml . We are using the rule of $RELAYING_PARY/openid of ADFS to get extended tokens (we have tried the standard one without success).

If anyone is interested, these are the full logs: https://hasteb.in/esuzewof.json

Thank you very much for this incredible tool. It's amazing :D

**Comment by bnfinet** [comment] 2020-04-29 17:36
@tangel0v thanks for the kind words

Please do post your full logs in the manner described in the README. (`testing`,`debug`)

**Comment by tangel0v** [comment] 2020-05-02 15:33
Hi to all and sorry for my late answer, here are the full logs: https://hasteb.in/osomazob.lua with testing and debug.

Thank you very much

**Comment by bnfinet** [comment] 2020-05-04 19:12
`Error unmarshaling claims` implies that this is not readable JSON, which is correct since `OpenID userinfo body: ` implies that the body is empty.

Have you confirmed the `user_infor_url`?

**Comment by tangel0v** [comment] 2020-05-06 05:38
Yes, another OAuth applications are working against that user_info endpoint.

In ptokens, the token is valid if you decrypt them.

**Comment by bnfinet** [comment] 2020-05-06 05:53
Why isn't user_info_url returning anything to VP?

**Comment by bnfinet** [comment] 2020-05-16 20:55
@tangel0v any progress on determining why that return is blank?

If there were any issue with VP I'd expect to see other reports of similar ADFS problems.  Unfortunately I'm not in a position to test ADFS personally.

**Comment by tangel0v** [comment] 2020-05-17 10:22
Hi @bnfinet I paused the tests during a week because of my workload but I have restarted it yesterday. I already don't know why the answer is blank but I'll provide you any information I get

**Comment by bnfinet** [comment] 2020-06-01 21:39
@tangel0v have you had an opportunity to test this further?

You may be able to get an indication by running the Alpine image in k8s and then curl'ing the `user_info_url`.

**Comment by bnfinet** [comment] 2020-07-07 22:30
@tangel0v have you had any opportunity to work on this?  If you will not be pursuing this issue at this time would you please close it?

**Comment by bnfinet** [comment] 2020-07-13 17:31
@tangel0v I'm going to close this, please do let me know if you'd prefer to re-open to work on the issue further.

**Closed by bnfinet** 2020-07-13 17:31 UTC
Labels: question
