### ISSUE TITLE
make OAuth IdP refresh token requests to keep the user logged in

### ISSUE THREAD

**Issue by ssudame** [vouch/vouch-proxy#149] opened 2019-09-17 16:04 UTC
Does vouch_proxy refresh access token when it's getting close to expiration? Can it get refresh token (assuming offline_access in scope) - that can be used to refresh expiring access token.  What needs to be changed in the code to enable such feature?

**Comment by bnfinet** [comment] 2019-09-18 12:51
Vouch Proxy does not make use of a refresh token.  I would support a PR if you cared to work on this but there's some other structural concerns...

Part of the problem is where to store a refresh token.  Right now VP is mostly stateless.  Every request relies on parsing the JWT Cookie to determine state.  If we held the refresh token for each user we would either expand the Cookie, possibly beyond the per domain cookie size limitations of some browsers

#111 , #109 and #125 are related

**Comment by bnfinet** [comment] 2019-10-10 18:16
After some consideration we've decided to take this off the roadmap, at least for now.  We've discussed this on IRC and we're not sure of the utility of a refresh token vs. just asking the user to go log in again.  Because of the long lived nature of refresh tokens we see it as a potential exposure to carry the refresh token in VP.

I'm going to close this for now but please (anyone) do let us know if you have a strong argument for inclusion of this feature.

**Closed by bnfinet** 2019-10-10 18:16 UTC
Labels: enhancement, help wanted

**Comment by nichogenius** [comment] 2022-11-14 23:36
@bnfinet 

I would like to argue for refresh token support.

There is value in short-lived access tokens.  If an access token is only valid for 5 minutes, a user's access can be revoked without having to wait for longer than 5 minutes.

There is value in long-lived tokens.  If a token only lasts 5 minutes, a user must login again every 5 minutes.  This isn't too bad if your IdP allows cookie based authentication, but If your IdP doesn't allow cookie based authentication AND incorporates 2FA, this quickly becomes impractical.

There is value in being able to move control from the vouch-proxy configuration to the IdP.  The IdP can dictate the length of the refresh tokens, so the IdP maintains greater control over the lifetime of the user's access.

With refresh tokens, you can have it all.  Short lived tokens, seamless session continuity for long durations, and removal of any session durations limits from the vouch-proxy config.

Refresh tokens are also an important tool when trying to deploy apps with security compliance requirements.

**Comment by aaronpk** [comment] 2022-11-14 23:41
Refresh tokens are not meant to be used to indicate session lifetime of consuming applications. Both access tokens and refresh tokens are used when a client accesses protected resources. Vouch uses OAuth only as an SSO mechanism, and does not make use of access tokens other than when an IdP doesn't support OIDC but has its own mechanism for retrieving user info after login. Refresh tokens don't make sense in this scenario at all. Instead, Vouch sets its own session lifetime after retrieving the user info. If you wanted to couple Vouch session lifetime to IdP session lifetime, that would be a different discussion to have, but also would not involve refresh tokens at all.

**Comment by nichogenius** [comment] 2022-11-15 00:48
I guess the functionality that I am missing is I don't have a way for my IdP to revoke access to a resource without having a very short Vouch session duration and forcing a redirect to the IdP.  The use case I am describing is more of an authorization concept than an authentication concept as you pointed out, so it falls outside of the scope of what Vouch is designed to do.

For my application, I have:
Web Client
-> Nginx proxy layer 1 - Vouch-Proxy function as an OIDC client to a Keycloak IdP
-> Nginx proxy layer 2 - PHP script invoked via auth_request subrequest that performs role based access control
-> Company owned private resource

What I should do is extend my PHP role authorization script to use the id token to obtain an access token.  If an access token is unable to be obtained or refreshed, then deny the request.

**Comment by bnfinet** [comment] 2023-01-16 17:42
From #517 
```
Here is my argument: i work on some database app and make changes, more frequently than, suppose, an hour. and i know that auth timeout is an hour. i've subbmited some data few minutes ago and want to submit some more, but suddenly my app throws me at IdP page, saying i must reauthenticate, loosing just submitted data.
Very frustrating user expirience.

Please, consider implementing refresh tokens as standart suggests.
```

**Comment by mig5** [comment] 2023-01-19 22:51
Since this issue is closed, maybe further discussion can take place in #319 ?

**Comment by bnfinet** [comment] 2023-01-19 23:21
@mig5 #319 is slightly different in that is passing a refresh token to a protected app, this is about keeping someone logged in.

This issue is closed because until there's a viable way to do this I'm not interested in including it in a roadmap tagged as 'enhancement' or 'help wanted'.  I'm fine with having the discussion here for the time being.

Please do let me know if you see a viable implementation.

**Comment by bnfinet** [comment] 2023-01-19 23:30
copied from @mig5 #319 (I've deleted the comment there)

This does sound like it would maybe help address my problem described in #499 (comment) , which I think echoes this comment: #149 (comment)

In short, doing a POST submission of a form on a site that is protected by Vouch, is catastrophic if the jwt has expired, as the POST payload is lost.

If the submission of the POST request saw Vouch obtain/pass/renew a refresh token as part of the request, (crucially, without any redirect in the user's browser), I imagine/hope the POST payload would be retained and the original request submit intact.

**Comment by bnfinet** [comment] 2023-01-20 05:39
@mig5 and others..

My preferred implementation would be to capture the `POST`, hold it in a session cookie during a login flow and then trigger a redirect back into the `POST`.

Unfortunately that's hard...
https://stackoverflow.com/questions/40645270/nginx-auth-request-handler-accessing-post-request-body
https://stackoverflow.com/questions/46582/response-redirect-with-post-instead-of-get

perhaps not impossible, but definitely doing HTTP backflips.

This implementation seems promising, though it's javascript dependent.
https://github.com/heroku/kensa/blob/d4a56d50dcbebc2d26a4950081acda988937ee10/lib/heroku/kensa/post_proxy.rb
