### ISSUE TITLE
When opening the protected site in multiple tabs, login only works for the latest tab

### ISSUE THREAD

**Issue by gsx95** [vouch/vouch-proxy#349] opened 2021-01-12 13:22 UTC
Hi,
we are working with vouch and we face a problem when opening multiple tabs of our protected domain at the same time.
In all tabs, vouch is correctly redirecting to the login page of our OIDC provider. When logging in in any Tab **but the latest one** the user is presented with an vouch error page and the logs are stating `Invalid session state: stored chQloRMDHm5ZYLphOV6t399uBrrXImhR, returned sUFYYSiL52WTNBJv9KiZsYOBcvbWBgYg`.

We believe that this is the case because each of the opened login tabs have a different state in its URL, and because only the state of latest tab is stored in the cookie (because it is overwritten every time on /login), the subsequent state check fails for all but the latest tabs.

Debug logs, Vouch config and the content of testing pages of two tabs are pasted [here on hastebin](https://hastebin.com/ibutogixed.pl) and as a [gist](https://gist.github.com/gsx95/23f0e29e729ca6c305a53712fd09f6a9). Let me know if you need something else. 

We think that this is expected behavior, is that correct? 
Is there a way around this?

This is really uncomfortable for users who are not logged in yet, open multiple tabs of our website and login with one of them.
Thanks in advance!

**Comment by aaronpk** [comment] 2021-01-12 14:14
@bnfinet this is closely related to the bug I experienced with the favicon loading too, and i had an idea of how we might be able to handle this.

**Comment by bnfinet** [comment] 2021-01-12 17:27
@gsx95 thank you so much for the detailed report!

And thanks for reaching out on IRC @fbuchmeier

Yes this is expected behavior.  I agree it is annoying behavior.  The common case is that someone has put their machine to sleep overnight and comes back in the morning, puts down the coffee and wants to get back to work.  All of the sudden their tabs are a mess.  I struggle with this myself.

My first question is.. if we re-use the same `state` value for multiple requests (each tab in this case) are we exposing ourselves in some manner?  Is there a replay attack or a way a bad actor could inject themselves here?

But there's another problem if we start handing out the same `state` param in the session cookie.  On each `/login` request the `url` param which sets the original destination is also stored in the session cookie.  That too gets written over on each `/login` call.

How do we ensure that each of the tabs reaches its intended destination?  Cookies are not tab specific. [1]

* /login?url=https://secretapp.yourdomain.com/tabA
* /login?url=https://secretapp.yourdomain.com/tabB

We could associate each state to a url and then if the `/login` request has an existing session cookie append a new `state: url` pair to an array of states and issue back the amended cookie.  But that feels like its going to be riddled with race conditions.  We could do something fancy on the server side to try to align those requests if they show up within a few seconds say but that's starting to feel a bit too far out on the limb.

We could 302 bounce each `/login` request to something like `/login/authcycle/$STATE?url=$TABa` and then set the state cookie directly into this `path` [2] .  But how do you get back there to retrieve the cookie and the URL?  The IdP will flow back to the `/auth` endpoint.

There may be a way to recover the URL using the html history API [3] but we've never used javascript in the flow.  I'm remiss to make that a requirement.

@aaronpk I'd love to hear your thoughts as always.

[1] https://stackoverflow.com/questions/27137562/tab-specific-cookies-without-using-sessionstorage-or-any-html5-features
[2] https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_where_cookies_are_sent
[3 https://www.w3schools.com/JS/js_api_history.asp

**Comment by bnfinet** [comment] 2021-01-12 17:34
Oh I'm not thinking what else the IdP returns.  The $STATE nonce!

okay, this solution could work.  after `/auth` we would 302 bounce to `/login/authcycle/$STATE?recover=yes` and that 302 bounces back to the intended destination.

@gsx95 would you be interested in supporting a PR for this effort?

**Comment by bnfinet** [comment] 2021-01-12 17:44
there are several related issues .. 
#348 session variable size 
#109 overall cookie size 
#334 each `/login` request clears existing cookies (`/login` is considered declarative and authoritative for "I am logging in")

**Comment by gsx95** [comment] 2021-01-12 22:30
Hi @bnfinet,
thanks so much for your quick insight and ideas. I would be glad to help fix this issue. 
I followed your suggestion above and that worked great. I created a PR for this which we can use for further discussions. There are still things that need to be done, and I am not so sure about some things, but at least we can speak about specific code now.

**Comment by bnfinet** [comment] 2021-01-13 20:51
@gsx95 awesome stuff!  Thanks for the quick turn around.

I'm expecting to take a closer look at this tomorrow. 

It occurred to me yesterday that this will require modification to any setups which use the "single-file" manner where VP is served from the same domain as the protected app...

https://github.com/vouch/vouch-proxy/blob/master/examples/nginx/single-file/nginx_with_vouch_single_server.conf#L41

**Comment by gsx95** [comment] 2021-01-13 21:16
Oh shoot, hadn't thought of that. 
Although if the nginx config in those setups are exactly as in the example you linked, this should work by not using a completely new endpoint but rather something like `/login/userauth` like you suggested yesterday, which would still be matched by the `location ~ ^/(auth|login|logout|static)`.
Will commit a fix for this in the PR tomorrow.

**Comment by gsx95** [comment] 2021-01-14 12:21
I updated the PR, let me know what you think. I'm relatively sure this does not break existing setups :)

**Comment by bnfinet** [comment] 2021-01-15 02:26
@gsx95 that all looks really straight forward.  I'm so glad to hear it's working.

I'm OOO and (mostly) AFK for a few days here, back at it on Wednesday next week.  I want to take a moment to test this.  It's unlikely to get merged before late next week.

Which browsers & platforms have you tested this on at this point?

Thank you for the code and the time.  This is a wonderful improvement of VP.

**Comment by gsx95** [comment] 2021-01-18 18:34
I tested on 

MacOS 11.1:
 - Firefox 84.0.2
 - Safari 14.0.2
 - Chrome 87.0.4280.141
 
iOS 14.3:
- Safari
 
 Windows 10:
 - Firefox 84.0.2
 - Chrome 87.0.4280.141
 - Internet Explorer
 - Edge 87.0.664.75
 
 Works fine for all of them, should maybe test on a linux distro too.

**Comment by bnfinet** [comment] 2021-01-21 03:08
@gsx95 thanks for the good code.  This feels like a big win for VP!

**Closed by bnfinet** 2021-01-21 03:08 UTC
Labels: enhancement, help wanted

**Comment by bnfinet** [comment] 2021-01-21 03:22
and I should add...

Tested on Linux with KDE neon 5.20 (Ubuntu Focal based)
* Firefox 83.0
* Chromium 87.0.4280.141
