### ISSUE TITLE
Question: will it work for our case?

### ISSUE THREAD

**Issue by leshik** [vouch/vouch-proxy#153] opened 2019-09-30 09:11 UTC
Hi,

I'm trying to choose between `vouch-proxy`, `oauth2-proxy`, or writing our own custom solution. Please, help me understand if `vouch-proxy` will work for our use case (and if not, what should be done to implement the required functionality.)

We have many geographically distributed web servers, each on its own subdomain under `domain1` (thus, not a single `nginx` config), as well as the same amount of subdomains on a cloud server, but under `domain2`. Now all of them authenticate with Google Sign In (Sign In with Apple is planned too), and we're forced to configure the callback and redirect URLs for every subdomain and host. This approach doesn't scale, especially with Apple limit of max 10 redirect URLs.

I wonder if `vouch-proxy` could help us to setup the single `auth.some-domain` URL to make authentication work for every host. Our app is React.js (frontend) + Ruby GraphQL API (backend), and JWT tokens are used for authentication.

**Comment by artagel** [comment] 2019-09-30 09:21
Vouch is designed to be like an authentication gateway to other services.  So if you had, for example, an unauthenticated service sitting at service.domain1.com, you could put vouch in front of it, and have people authenticate to google and then if they are authenticated, proxy the connection to service.domain1.com.  At this point, on service.domain1.com, you'd restrict access on the IP level only to your vouch proxy.

In you situation, you want to use vouch as an auth gateway to pass down what sounds like a JWT token.  Depending on how and where that JWT token comes from, this is possible.  We can pass access tokens to the downstream websites.  We can technically pass any 'claim' provided by your auth provider (such as username, email, etc) down to the downstream websites.  So the critical question is where does the JWT come from, and how does your downstream service authenticate it?

**Comment by leshik** [comment] 2019-09-30 09:43
@artagel thank you for the quick reply!

Initially, JWT is created by the backend API, then frontend gets it by GraphQL when a user logs in. Then frontend adds `Authorization: Bearer ...` header to every request. Besides Google Sign In, we also have non-oauth2 users who should be able to authenticate with a login/password pair (thus they also need JWT.) But we can change the implementation to make it compatible with `vouch-proxy` if necessary.

**Comment by artagel** [comment] 2019-09-30 10:51
But your backend API is generating the JWT based on an authenticated session from google right(except non-oath2 users).  If you change your downstream systems to use some kind of user authentication or identification mechanism passed by vouch, then you are golden.  Otherwise, they'd have to authenticate again, which puts you back in your original problem.  

So for example, vouch is validating your user is authenticated to google, and it can get any claims.  So if you app is user auth based, then vouch could send down the authenticated username, at which point you would read that header and use it as an authentication mechanism.  Similar to the way the bearer token works.  

I'm not 100% sure how the tokens work with google, but potentially you could also send down the token received from the google auth and send it down as a Bearer token immediately, but your app would have to know how to validate it.

**Comment by artagel** [comment] 2019-09-30 10:56
By the way, oauth2-proxy essentially works the same way as vouch, using NGINX to send an auth request to a third part auth service and then allowing the traffic down if the auth is successful...  
So whichever product you choose, the problem is the same.  Vouch has more options and customization when it comes to being able to send additional info to downstream websites, IMO.

**Comment by leshik** [comment] 2019-09-30 11:47
Thank you for your thorough reply @artagel, we’ll definitely give vouch a try! I’ll let you know how it goes.

**Comment by artagel** [comment] 2019-09-30 13:40
No worries :)  Just remember if you are using a username or something similar in headers downstream to identify the user, you absolutely need to make sure that your downstream sites only allow traffic from your proxy, otherwise, someone could easily forge the headers and impersonate other users.
If your question is answered, you can close the issue.  You can always open another one if you get stuck.
Cheers!

**Closed** 2019-09-30 13:46 UTC
