### ISSUE TITLE
Vouch isn't passing groups claim downstream

### ISSUE THREAD

**Issue by kazigk** [vouch/vouch-proxy#340] opened 2020-12-07 16:47 UTC
**Use a Paste Service**
Here's a [log](https://hasteb.in/dadevazi.log). I had to strip some sensitive data, but I left what's relevant.

**Describe the problem**
I have Vouch Proxy configured to forward the groups claim downstream.
The groups are in the JWT token, but for some reason Vouch Proxy is not forwarding them.

**Desktop (please complete the following information):**
not relevant, but
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.198 (Official Build) (64-bit) (cohort: Stable)

**Vouch version**
`v0.18.0` downloaded from GitHub Releases, built using `go version go1.13.15 linux/amd64`

**Additional context**
I'm using Azure provider, maybe the Vouch doesn't like the format Azure is using?

That's the format Azure is using in JWT:
```
"groups": [
    "1f4b68ea-19e1-43c5-8397-ddcd892ca4a0",
    "0e204e43-9e26-400c-bd2b-71ee1c9da7ad"
],
```
(a list of UUIDs)

**Comment by bnfinet** [comment] 2020-12-07 22:42
I suspect this is azure specific

@kazigk could you please post your config and logs in the manner described in the README to a gist

**Comment by kazigk** [comment] 2020-12-08 00:59
Sure, however bug_report doesn't work for me. I can create a fresh test environment and post full logs if this would help. Right now I'm testing with my company's AAD, so I have to redact everything.

[Output of bug_report](https://hasteb.in/qudisuhu.yaml)
(I had to redact tenant id from URLs, everything else is left intact)

[Nginx config for my test app](https://hasteb.in/icavuyek.nginx)
[Nginx config for Vouch](https://hasteb.in/amelowon.nginx)

**Comment by bnfinet** [comment] 2020-12-08 01:06
@kazigk without a complete log, full roundtrip w/ debug and testing I'm not able to see where the problem is or any of VP's behavior

**Comment by kazigk** [comment] 2020-12-08 01:13
I will update you with complete log today or tomorrow. Thank you for your help!

**Comment by bnfinet** [comment] 2020-12-08 01:44
@kazigk thanks that'll very helpful
 
If you're in a position to improve `./do.sh bug_report`'s  `_redact()` routine, I'm happy to have additional patterns or full `sed` calls for better and easier bug reporting

**Comment by kazigk** [comment] 2020-12-10 08:55
@bnfinet I could work on this in the future, but I'm not promising anything.

I hope [this gist](https://gist.github.com/kazigk/ad55cc74bcc022f839183d128ade8a35) is everything you need. Full log, configs and some useful things. This is my test environment, so I don't need to care about any sensitive data.

**Comment by RishabhAsthana** [comment] 2020-12-11 15:06
@kazigk are the groups in the id_token or access_token?
In my case, they were always in id_token so I had to change some logic around to make Vouch get group claims from user id_token instead. This was after getting frustrated with the Azure AD documentation and several days of trial and error, so this may very well be unorthodox in terms of OAuth

**Comment by kazigk** [comment] 2020-12-12 19:24
I got the groups from `X-Vouch-IdP-IdToken` header after using jwt.io tool. If there's anything else I can do, please let me know. Unfortunately Golang isn't on my list of languages I speak, so I can't do much by myself

**Comment by RishabhAsthana** [comment] 2020-12-17 16:19
<img width="1878" alt="Screen Shot 2020-12-17 at 10 16 22 AM" src="https://user-images.githubusercontent.com/22674480/102513686-24459280-4051-11eb-81de-d5b1bee1f686.png">

This is all I did to get groups from the id_token instead

**Comment by kazigk** [comment] 2020-12-18 10:08
Thank you @RishabhAsthana! I will test it and let you know if it works

**Comment by kazigk** [comment] 2020-12-27 08:39
@RishabhAsthana First of all, your code works and you are my hero!

I also tried to get it working with access token. Just out of curiosity. And...
You're right. Groups are not in access token. After reading [this](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/a211126f-dff3-416c-a568-46f9a863d282/groups-not-in-access-token?forum=WindowsAzureAD) and [this](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent) I tried to change permissions and the scope. I had no idea how to get groups in access token. And then I noticed the `ver` in id token is `2.0` and in access token it's `1.0`. That might be the issue but I have no idea how to investigate it further. This [documentation page](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens) looks helpful.

I'm sticking to @RishabhAsthana solution. In Azure I can set up the claims I need both for auth and id token, so that totally works for me. I wanted to share my findings tho.

**Comment by kazigk** [comment] 2020-12-27 08:57
Oh, I just noticed there is PR #320 allowing to use preferred token. The mentioned PR solves this issue.

**Comment by RishabhAsthana** [comment] 2020-12-27 21:22
Nice find! Hope that gets merged soon

**Comment by bnfinet** [comment] 2020-12-28 04:37
@RishabhAsthana and @kazigk could you please join the discussion on #314 

I would like to merge #320 but I haven't had anyone post a successful test.  If you could please post a full working log to that thread it would be much appreciated.

I am not an Azure user.

**Comment by kazigk** [comment] 2020-12-28 06:59
@bnfinet I need to prepare multi-tenant environment to test this. I will update you with a comment on the issue you mentioned. Happy New Year everyone! 🍾

**Comment by bnfinet** [comment] 2020-12-28 08:21
@kazigk thank you!  That would be very helpful.

Happy New Year to you and yours as well!

**Comment by bnfinet** [comment] 2021-02-03 18:36
@kazigk friendly reminder of #314 and #320.  I'm hoping someone can post a working config and log (or a non-working log). I would love to move that along in either direction.  I hope that wouldn't take more than a half hour or so.  Cheers!

**Comment by iamareuben** [comment] 2021-03-05 07:34
I tried to run #320 authenticating against an Azure AD with guest users, and had a bunch of errors.  I'm fairly new to Go, and I want to strip my project down to a minimum working example so will aim to post logs tomorrow, and potentially have a look at the code to see if I can figure out what's going on.

**Comment by iamareuben** [comment] 2021-03-06 04:01
@bnfinet I've posted a working config and log to #320 with a small change to the code.

**Closed** 2021-06-01 17:32 UTC
Labels: question

**Comment by Siva-Taicho77** [comment] 2024-07-31 12:10
Hi @bnfinet 

I am still facing this issue, my vouch proxy is not passing the groups claims to the downstream servers.

**Comment by bnfinet** [comment] 2024-07-31 16:14
@Siva-Taicho77 please open a new issue and post the requested information as described in the README.
